### ISSUE TITLE
Dashboard to assign users

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#741]
- [ ] Dashboard to assign users to specific locations (ui-select)
  - [ ] Start with the user, and then assign to the city block
  - [ ] Display the user's neighborhood
  - [ ] Automatically list all city blocks associated with the user's neighborhood. They will need to click it to assign to it.
- [ ] UX: facilitators must first select a neighborhood, then it will list all users, then it will ask them to assign to a specific city block

**Comment by cdparra** [comment]
Deprecated in favor of the newly developed #868
