### ISSUE TITLE
Chart data endpoints are not working properly and should return the last 3 months of "active" data

### ISSUE THREAD

**Issue by cdparra** [socialappslab/denguetorpedo#960]
"Gráfico de casas verdes" y "Cambio en Riesgo en Tu Barrio.." look empty in Asunción because the last three active months were in 2019, but we need to show those last three months in the charts. 

![image](https://user-images.githubusercontent.com/630150/87681333-8d487780-c74c-11ea-9d7f-e8df9a291dd8.png)

@gvescu has updated the services to provide this response, but they are having issues. 

`GET https://www.denguechat.org/api/v0/graph/green_locations?city=9` is returning error 500

![image](https://user-images.githubusercontent.com/630150/87681477-b23cea80-c74c-11ea-9b1a-514354ef79c4.png)

Fixe the endpoint and make sure it returns the 3 last active months

**Estimated effort: ** 5h

**Comment by sofiarivas93** [comment]
This issue is already solved...
![image](https://user-images.githubusercontent.com/18225410/102702735-b497f900-4244-11eb-8542-38956cf6fcec.png)
